github:
  repo: JonnyJD/musicbrainz-isrcsubmit

issues:
  url: http://github.com/JonnyJD/musicbrainz-isrcsubmit/issues

downloads:
  url: http://isrcsubmit.jonnyjd.net/downloads/

script:
  name: isrcsubmit
  version: 0.5.2
  current: isrcsubmit-0.5.2

nav:
- title: home
  url: ./
- title: download
  url: download
- title: install
  url: install
- title: changes
  url: changes
- title: bugs
  url: bugs
- title: backends
  url: backends
- title: links
  url: links
