github:
  repo: JonnyJD/musicbrainz-isrcsubmit
  raw: https://raw.github.com/JonnyJD/musicbrainz-isrcsubmit/

issues:
  url: https://github.com/JonnyJD/musicbrainz-isrcsubmit/issues

downloads:
  url: http://isrcsubmit.jonnyjd.net/downloads/

script:
  name: isrcsubmit
  old_version: 1.0.2
  old: isrcsubmit-1.0.2
  version: 2.1.0
  current: isrcsubmit-2.1.0

nav:
- title: home
  url: ./
- title: download
  url: download
- title: install
  url: install
- title: changes
  url: changes
- title: bugs
  url: bugs
- title: backends
  url: backends
- title: links
  url: links
