github:
  repo: JonnyJD/musicbrainz-isrcsubmit

issues:
  url: http://github.com/JonnyJD/musicbrainz-isrcsubmit/issues

downloads:
  url: http://isrcsubmit.jonnyjd.net/downloads/

script:
  name: isrcsubmit
  version: 1.0.1
  current: isrcsubmit-1.0.1
  pre_version: 2.0.0-beta.3
  pre: isrcsubmit-2.0.0-beta.3

nav:
- title: home
  url: ./
- title: download
  url: download
- title: install
  url: install
- title: changes
  url: changes
- title: bugs
  url: bugs
- title: backends
  url: backends
- title: links
  url: links
